### ISSUE TITLE
Letta 0.9.1 doesn't work with latest ollama

### ISSUE THREAD

**Issue by srd00** [letta-ai/letta#2739]
**Describe the bug**
Regression, after update to newest 0.9.1, Letta fails to get model context window and embedding dimension for all models in ollama

**Please describe your setup**
Windows setup, running on docker with the following command
  `docker run --rm -p 8283:8283 -e LETTA_PG_URI=<uri> -e OLLAMA_BASE_URL="http://host.docker.internal:11434" local/letta:0.9.1`

**Additional context**
Relevant log:
``
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for hf.co/unsloth/Qwen3-14B-GGUF:Q8_0
Ollama model hf.co/unsloth/Qwen3-14B-GGUF:Q8_0 has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for hf.co/nomic-ai/nomic-embed-text-v1.5-GGUF:F16
Ollama model hf.co/nomic-ai/nomic-embed-text-v1.5-GGUF:F16 has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for hf.co/gaianet/Nomic-embed-text-v1.5-Embedding-GGUF:F16
Ollama model hf.co/gaianet/Nomic-embed-text-v1.5-Embedding-GGUF:F16 has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for hf.co/gabriellarson/Phi-mini-MoE-instruct-GGUF:Q8_0
Ollama model hf.co/gabriellarson/Phi-mini-MoE-instruct-GGUF:Q8_0 has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for hf.co/brittlewis12/Phi-3-mini-4k-instruct-GGUF:Q8_0
Ollama model hf.co/brittlewis12/Phi-3-mini-4k-instruct-GGUF:Q8_0 has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for llama3.2-vision:latest
Ollama model llama3.2-vision:latest has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for llama4:scout
Ollama model llama4:scout has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for nomic-embed-text:latest
Ollama model nomic-embed-text:latest has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for marco-o1:latest
Ollama model marco-o1:latest has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for phi4:latest
Ollama model phi4:latest has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for phi3.5:latest
Ollama model phi3.5:latest has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for deepseek-r1:latest
Ollama model deepseek-r1:latest has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for gemma3:latest
Ollama model gemma3:latest has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for gemma3:27b
Ollama model gemma3:27b has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for phi4-mini:latest
Ollama model phi4-mini:latest has no context window
Letta.letta.schemas.providers.ollama - WARNING - Failed to get model context window for exaone-deep:latest
Ollama model exaone-deep:latest has no context window
Ollama model hf.co/unsloth/Qwen3-14B-GGUF:Q8_0 has no embedding dimension
Ollama model hf.co/nomic-ai/nomic-embed-text-v1.5-GGUF:F16 has no embedding dimension
Ollama model hf.co/gaianet/Nomic-embed-text-v1.5-Embedding-GGUF:F16 has no embedding dimension
Ollama model hf.co/mradermacher/Seed-X-Instruct-7B-GGUF:latest has no embedding dimension
Ollama model hf.co/bartowski/Llama-3.2-3B-Instruct-GGUF:Q8_0 has no embedding dimension
Ollama model hf.co/gabriellarson/Phi-mini-MoE-instruct-GGUF:Q8_0 has no embedding dimension
Ollama model hf.co/brittlewis12/Phi-3-mini-4k-instruct-GGUF:Q8_0 has no embedding dimension
Ollama model hf.co/mradermacher/Mistral-7B-Instruct-v0.3-GGUF:Q8_0 has no embedding dimension
Ollama model hf.co/mradermacher/Mistral-7B-Instruct-v0.3-GGUF:Q5_K_S has no embedding dimension
Ollama model hf.co/mistralai/Magistral-Small-2507-GGUF:Q5_K_M has no embedding dimension
Ollama model llama3.2-vision:latest has no embedding dimension
Ollama model llama3.2:latest has no embedding dimension
Ollama model llama4:scout has no embedding dimension
Ollama model nomic-embed-text:latest has no embedding dimension
Ollama model llama3.2:3b has no embedding dimension
Ollama model marco-o1:latest has no embedding dimension
Ollama model phi4:latest has no embedding dimension
Ollama model phi3.5:latest has no embedding dimension
Ollama model deepseek-r1:latest has no embedding dimension
Ollama model gemma3:latest has no embedding dimension
Ollama model gemma3:27b has no embedding dimension
Ollama model phi4-mini:latest has no embedding dimension
Ollama model exaone-deep:latest has no embedding dimension
Ollama model llama3.3:latest has no embedding dimension
``

Server then shutdown with Internal Server Error

**Local LLM details**

If you are trying to run Letta with local LLMs, please provide the following information:

ollama is local latest ollama/ollama:0.10.1 but this happened on the previous 0.9.? version

**Comment by cliandy** [comment]
hi, this should be fixed in the next release. Thanks for your patience.

**Comment by srd00** [comment]
Pinpointed the issue on methods of OllamaProvider in ollama.py.

In get_model_context_window it checks for "llama.context_length" when the new ollama answers with "<general.architecture>.context_length" and in _get_model_embedding_dim_async Letta checks for "embedding_length" when it now is "<general.architecture>.embedding_length"

**Comment by t83714** [comment]
had the same problem with 0.9.1 and can confirm that [v0.10.0](https://github.com/letta-ai/letta/releases/tag/0.10.0) works for me

**Comment by antondevson** [comment]
It doesn't fail anymore but it still doesn't work, it just sets the default context window of `32000` for every model, and `1024` for every embedding fetched. I made a PR for it here https://github.com/letta-ai/letta/pull/2743.

It's still not optimal as there no obvious way to distinguish between LLMs and embeddings from the Ollama API, that I'm currently aware of, and they're all fetched for either endpoint in Letta.

There's also a lot of refactoring and cleanup that could be done, but I'm not sure if you guys do that separately from bug fixes or not.

**Comment by srd00** [comment]
> It doesn't fail anymore but it still doesn't work, it just sets the default context window of `32000` for every model, and `1024` for every embedding fetched. I made a PR for it here [#2743](https://github.com/letta-ai/letta/pull/2743).
> 
> It's still not optimal as there no obvious way to distinguish between LLMs and embeddings from the Ollama API, that I'm currently aware of, and they're all fetched for either endpoint in Letta.
> 
> There's also a lot of refactoring and cleanup that could be done, but I'm not sure if you guys do that separately from bug fixes or not.

Actually there's the "capabilities" info, embedding models have "embedding" in "capabilities" while chat models have "completion".

The relevant keys in the /api/show response are the following:

"model": "llama3.2:latest"
`{
    "model_info": {
        "general.architecture": "llama",
        "llama.context_length": 131072,
        "llama.embedding_length": 3072
    },
    "capabilities": [
        "completion",
        "tools"
    ]
}`

"model": "nomic-embed-text:latest"
`    "model_info": {
        "general.architecture": "nomic-bert",
        "nomic-bert.context_length": 2048,
        "nomic-bert.embedding_length": 768
    },
    "capabilities": [
        "embedding"
    ]
}`

AFAIK in the recent ollama versions the "general.architecture" value is always prepended on context_length and embedding_length keys, that's why the keys are different ( "llama.context_length" and "nomic-bert.context_length", etc)

**Comment by antondevson** [comment]
> Actually there's the "capabilities" info, embedding models have "embedding" in "capabilities" while chat models have "completion".

You're right, must have missed that! The above PR is already merged so I'll make another one to fix this as well.

**Comment by antondevson** [comment]
Okay the above issue has a fix now too, https://github.com/letta-ai/letta/pull/2744.

There is one more optimization in briefly caching the responses from `/api/show` from the Ollama server since they're still somewhat large, but it's likely much more trouble than it's worth at this point. Only use case that would be noticeably affected is running Ollama with a lot of models over a slow connection to the Letta server.

**Comment by antondevson** [comment]
This issue should also be resolved now @srd00

**Comment by zh-impact** [comment]
Letta server // v0.11.7 with Ollama 0.11.10 Still occurs this error again:
```python
Letta.letta.otel.db_pool_monitoring - INFO - First connection established for engine: default_async

Traceback (most recent call last):

  File "/app/letta/server/server.py", line 1571, in get_provider_embedding_models

    return await provider.list_embedding_models_async()

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/letta/schemas/providers/ollama.py", line 86, in list_embedding_models_async

    embedding_dim = await self._get_model_embedding_dim(model["name"])

                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.11/site-packages/pydantic/main.py", line 991, in __getattr__

    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')

AttributeError: 'OllamaProvider' object has no attribute '_get_model_embedding_dim'

/app/letta/server/server.py:1576: UserWarning: An error occurred while listing embedding models for provider id=None name='ollama' provider_type=<ProviderType.ollama: 'ollama'> provider_category=<ProviderCategory.base: 'base'> api_key=None base_url='http://host.docker.internal:11434' access_key=None region=None api_version=None organization_id=None updated_at=None default_prompt_formatter='chatml': 'OllamaProvider' object has no attribute '_get_model_embedding_dim'
```
<img width="1419" height="1666" alt="Image" src="https://github.com/user-attachments/assets/a6310988-b26b-4317-8f8a-34059d00e488" />

<img width="372" height="65" alt="Image" src="https://github.com/user-attachments/assets/051fe379-e933-40e6-a4f5-c2ed85655eac" />

**Comment by antondevson** [comment]
@zh-impact this was a regression, a fix has been merged now with https://github.com/letta-ai/letta/pull/2775. It will be in the next release `0.11.8`
